---
# TODO they don't have versions for 17.10, gotta fix that somehow
# - name: add alternative python versions repository
#   become: true
#   apt_repository: repo=ppa:deadsnakes/ppa

# TODO add docker repo
# https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#set-up-the-repository

- name: install additional programs
  become: true
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - docker-ce
      # so that I can easily work with data on an Android phone
      # TODO how's MTP on arch?
    - go-mtpfs
    - hunspell
    - lxd # full-OS containers
    - pandoc
  # TODO fix when I solve the deadsnakes problem
  #  - python3.6
  #  - python3.6-dev
  #  - python3.6-venv
  #  - python3.5
  #  - python3.5-dev
  #  - python3.5-venv
  #  - python3.4
  #  - python3.4-dev
  #  - python3.4-venv
    - vagrant
    - vagrant-lxc
    - virtualbox
    - whois

- name: add user to docker group
  become: true
  user: name={{ ansible_env.USER }} groups=docker append=yes

- name: install python programs
  pip:
    name: '{{ item }}'
    executable: pip3
    state: latest
    extra_args: '--user'
  with_items:
    - awscli
    - awscli-plugin-endpoint
    - credstash
    - docker-compose
    - twine  # uploading Python packages

- name: install python 2 programs
  pip:
    name: '{{ item }}'
    executable: pip2
    state: latest
    extra_args: '--user'
  with_items:
    - molecule  # testing Ansible roles

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip
    dest: "{{ ansible_user_dir }}/bin"
    remote_src: True
