---
- name: american locale
  locale_gen: name=en_US.UTF-8 state=present

- name: polish locale
  locale_gen: name=pl_PL.UTF-8 state=present

- name: update package info
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_facts['os_family'] == 'Debian'

- name: upgrade debian system
  apt: upgrade=dist
  when: ansible_facts['os_family'] == 'Debian'

- name: upgrade arch system
  pacman: upgrade=yes upgrade_cache=yes
  when: ansible_facts['os_family'] == 'ArchLinux'
